### PR TITLE
[MERGE WITH GIT FLOW] Fix nightly update trigger improvements

### LINKED ISSUE #2390: Interim fix for the nightly itemized schedule updates
@LindsayYoung and I were discussing the impact of the nightly updates routinely failing and putting us in a perpetual state of requiring partitioning of the itemized schedule A and B data, and we came to the realization that there is a solution for a stop-gap fix until we're able to address the root cause of the issue (detailed in issues #2309 and #2227; we have a meeting setup with FEC folks next week).

The idea here is that we check for the presence of an empty recordset from the view before we process it and populate it in the designated queue tables.  [PostgreSQL provides a way to check for this easily](https://www.postgresql.org/docs/current/static/plpgsql-statements.html#PLPGSQL-STATEMENTS-DIAGNOSTICS), so we'll implement a hot fix to address it and at least get our nightly updates cleaned up now.

There's an additional task that we can do as a separate hot fix to keep track of which `sub_id`s fall into this state in a separate table and retry them at another time (e.g., a day later).  They'd remain in this table until the record is successfully processed, and it'll give us a bit more of a window into which records are falling into this state so we can understand why better.  Is it an expected thing (e.g., they don't exist in the corresponding `disclosure.f_item_receipt_or_exp` table) or something else?  It'll provide us with information to go on.

To recap:

* [x] Fix the nightly updates of itemized data by checking for empty resultsets before processing (#2392)
* [x] Add support for keeping track of and retrying failed `sub_id`s (#2398)

### PR DESCRIPTION
**Pull request by ccostino**
**MERGE WITH GIT FLOW**

Fixes #2390

This changeset addresses a couple of issues we uncovered with our last nightly update fixes.  First, the record was not being returned properly in the trigger function due to incorrect shuffling around of return statements.  Second, we now also track which sub_ids are not found and place them in a secondary queue.  This queue is processed separately and mirrors the functionality of the main queues with the exception that sub_ids will remain in here until the record can be processed successfully from the itemized views we have to process from.

These improvements are a stop gap measure to keep our nightly updates running smoothly until we can improve the overall processing of the itemized schedule data.

### CODE REVIEW

File: data/sql_setup/prepare_schedule_a.sql [hunk 1]
```diff
@@ -1,3 +1,15 @@
+-- Create table to hold sub_ids of records that fail during the nightly
+-- processing so that they can be tried at a later time.
+-- "sub_id" is not unique as we may have to process it multiple times.
+-- The "action" column denotes what should happen with the record:
+--    insert, update, or delete
+drop table if exists ofec_sched_a_nightly_retries;
+create table ofec_sched_a_nightly_retries (
+    sub_id numeric(19,0) not null primary key,
```
Comment (vrajmohan) [inline data/sql_setup/prepare_schedule_a.sql]: `primary key` appears to violate comment on line 3.

Comment (ccostino) [inline data/sql_setup/prepare_schedule_a.sql]: D'oh!  When I had worked through this more I realized we shouldn't ever have a `sub_id` in this table more than once, so I figured the `primary key` would be okay.  I'll update the comment to reflect that, thanks!

File: data/sql_setup/prepare_schedule_a.sql [hunk 2]
```diff
@@ -87,33 +164,52 @@ begin
...
+            -- so keep track of this sub_id if we haven't already so we can
+            -- try processing it again each night until we're able to
+            -- successfully process it.
+            raise notice 'sub_id % not found, adding to secondary queue.', old.sub_id;
+
+            delete from ofec_sched_a_nightly_retries where sub_id = old.sub_id;
+            insert into ofec_sched_a_nightly_retries values (old.sub_id, 'update');
         end if;
+
+        return old;
```
Comment (vrajmohan) [inline data/sql_setup/prepare_schedule_a.sql]: We should be returning `new` here.

Comment (ccostino) [inline data/sql_setup/prepare_schedule_a.sql]: *facepalm* you're right!

**Comment by ccostino** [comment]
@vrajmohan, @LindsayYoung, and @jontours - this is ready for a full review now, but I'd also like to give it one more look too before merging, I'll take a look later tonight!

**Comment by ccostino** [comment]
Ready for review and merge. :-)

File: data/sql_setup/prepare_schedule_a.sql [hunk 3]
```diff
@@ -14,6 +25,54 @@ create index on ofec_sched_a_queue_old (timestamp);
...
+
+            if two_year_transaction_period >= start_year then
+                -- Determine which queue(s) the found record should go into.
+                case schedule_a_record.action
+                    when 'insert' then
+                        delete from ofec_sched_a_queue_new where sub_id = view_row.sub_id;
+                        insert into ofec_sched_a_queue_new values (view_row.*, timestamp, two_year_transaction_period);
+
+                        delete from ofec_sched_a_nightly_retries where sub_id = schedule_a_record.sub_id;
+                    when 'delete' then
```
Comment (LindsayYoung) [inline data/sql_setup/prepare_schedule_a.sql]: Do we want to get rid of the view check and delete the record directly by sub id? That can be a follow up task if we want to get this moving sooner

Comment (ccostino) [inline data/sql_setup/prepare_schedule_a.sql]: That makes sense to me, but I think that should be a follow up task because there are a couple of ways to go about that. :-)
