### PR TITLE
Fix last cash on hand.

### LINKED ISSUE #1110: Verify totals on first candidate comparison table on elections page are correct

### PR DESCRIPTION
**Pull request by jmcarp**
Fix a typo mixing up starting and ending cash on hand. After this
change, fundraising totals on the election page are identical to the
corresponding totals on each candidate's detail page.

[Resolves #1110]

### CODE REVIEW

File: data/sql_updates/create_totals_house_senate_view.sql [hunk 1]
```diff
@@ -7,7 +7,7 @@ with last as (
     )
         cmte_sk,
         two_yr_period_sk,
-        coh_bop as cash_on_hand_end_period,
+        coh_cop as cash_on_hand_end_period,
```
Comment (LindsayYoung) [inline data/sql_updates/create_totals_house_senate_view.sql]: We check 2 fields for that because filers don't report that consistently 

Example:
openFEC/data/sql_updates/create_reports_house_senate_view.sql
```
coalesce(coh_cop_i, coh_cop_ii) as cash_on_hand_end_period,
```

**Comment by jmcarp** [comment]
Fixed. Out of the tables changed here, only the House/Senate table uses the two cash on hand variables, so the others didn't have to change.
